runtime: python39
service: api

env_variables:
  JWT_SECRET_KEY: "your-super-secret-jwt-key-change-this-in-production"
  FLASK_ENV: "production"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always 